BOARD_TAG    = mega2560 
BOARD_SUB    = m2560 
ARDUINO_PORT = /dev/ttyUSB0
EXTRA_FLAGS    = -std=c++11 -Wp,-w
AVRDUDE_OPTS   = -D
OPTIMIZATION_LEVEL=3
AVRDUDE_ARD_PROGRAMMER = stk500v2

USER_LIB_PATH := $(realpath ../common)

include /usr/share/arduino/Arduino.mk
